### ISSUE TITLE
Allow exporting of metadata files

### ISSUE THREAD

**Issue by ltommasini76** [latenitefilms/MetaburnerPro#1]
Hi,
my name is Luca and i'm an editor for film documentaries, mostly which have Archive footage. And this request is properly related to Archive footage. Consider having already assigned roles to different types of AF. For example, one role to the one coming from Associated Press, one for Reuteres, etc. Usually, when the film is finished, the production must calculate how much AF they have used from each Archive, in order to, i make it simple, pay them the right costs. 
It would be great to have Metaburner Pro show me the source of the AF i'm watching and also how long is that portion of AF. It would also be great if i could have from Mteaburner pro, the chance to get a sort of EDL, or Xls file, where i can have all the clip divided by Roles..so i can easly calculate the total for each archive. 
Usually, these tasks require lot of time..and it would be great, instead, to have something that can speed up this process. And in FCPX..which would be great considering no NLE around could give such service.
Thanks and have a  nice day ahead...

**Comment by latenitefilms** [comment]
Hi Luca,

Thanks for your detailed message! Greatly appreciated!

**Metaburner Pro** will only handle metadata burning into the screen (at this point anyway).

There are plenty of tools already to get metadata out of a FCPXML such as [Producers Best Friend](https://fcp.cafe/ecosystem/tools/#producers-best-friend). You can also use [CommandPost](https://commandpost.io) to export both a Timeline Index and Browser CSV. You might also be interested in [Music Reporter](https://www.automaticduck.com/#music-reporter).

My suggestion would be to just make of Smart Collections and CommandPost - you could export a CSV of only used Clips or a certain Role, etc.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, however if you didn't already know, you can now download a very early alpha build of Metaburner Pro on TestFlight. Check the website for details:

https://metaburner.pro/how-to-use/
