### ISSUE TITLE
FCP crashes when dragging the project on the "Drag Project Here" box

### ISSUE THREAD

**Issue by samplue** [latenitefilms/MetaburnerPro#3]
FCP crashes when dragging the project containing the Metaburner title on the "Drag Project Here" box. FCP also crashes when trying to export the fcpxml to the Desktop. Removing the Metaburner Title from the Timeline fixes the issue.

[2023-12-18_Metaburner_Crash_Log.rtf.zip](https://github.com/latenitefilms/MetaburnerPro/files/13702084/2023-12-18_Metaburner_Crash_Log.rtf.zip)

**Comment by latenitefilms** [comment]
This FCPX crash/bug has been reported here:

https://github.com/CommandPost/FCPCafe/issues/307

I'm going to close this issue for now, as I don't think there's anything we can do specifically about it in Metaburner Pro - as it's Final Cut Pro crashing, not our FxPlug.
